### PR TITLE
add xander's patches

### PR DESCRIPTION
**Pull request by MicrocontrollersDev**
## Description

From patcher's upstream pr number 28

the shader one was denied with a stupid reason and i see no reason why it shouldnt be added

~~the other one was denied under fears it may send a packet to server. i have no clue how to confirm nor deny this~~ removed for this reason

## Related Issue(s)

Fixes #

## Release Notes

```release-note
Fixed entering an entity in spectator mode while in third person applies shader
```

### CODE REVIEW

**Comment by Wyvest** [comment]
Remove the block breaking one, I am also slightly worried about that

**Comment by MicrocontrollersDev** [comment]
> Remove the block breaking one, I am also slightly worried about that

done

**Comment by Mixces** [comment]
> Remove the block breaking one, I am also slightly worried about that

Based on my understanding of the source code, I can conclusively say that it won't cause issues... I've also been using a modified version of this fix for the better part of 2 years in my private mod and I've been perfectly fine on all servers. 

Furthermore, the fix could be modified to also include Adventure mode rather than just Spectator mode as well. Minecraft _does_ actually check to see if the player has the ability to edit (aka in Survival Mode), however, the check (`isAllowEdit`) isn't in an effective place. 

The check is located at the top of `PlayerControllerMP#clickBlock`, and the clickBlock method is invoked within the `PlayerControllerMP#onPlayerDamageBlock` method which is where the actual problem arises. The game only invokes clickBlock at the **end** of onPlayerDamageBlock... and well... the section of code above this call basically checks to see if you had damage progress on the block and will send block-breaking packets and will return true. This is only the case with the _last_ block you were mining before you switched over to Spectator / Adventure mode. That means that whatever block you were mining before you switched to Spectator or Adventure mode will still be valid despite the fact that shouldn't be able to mine. If you were wondering why this issue doesn't happen with Creative Mode, well, the game actually checks for Creative mode at the top of onPlayerDamageBlock and acts accordingly.

Nevertheless, whatever you guys decide is best for the general population, I'll support it. I can totally understand why it's a worry to add this check although I personally am of the opinion that it will cause no harm.

**Comment by Mixces** [comment]
Actually now that I think of it, there is probably a safer way to do it without the fear of manipulating packets in a non-vanilla fashion 🤔

**Pull request merged**
